user_name = "nilaya"
email = "nayan+11@qxf2.com"
password = "nilaya1234"
new_user = "anonymous"

interviewers_name = "avinash"
interviewers_email = "avinash@qxf2.com"
interviewers_designation = "Manager QA"
interviewers_starttime_drop = "11:00"
interviewers_endtime_drop = "19:30"
search_option_interviewer = "avinash"

job_role = "Junior QA"
job_interviewers = "avinash"
search_option_job = "Junior QA"

name_candidates = "Mayara"
email_candidates = "test+100@qxf2.com"
job_applied_select = "Junior QA"
comment_candidates = "Nilaya's referral"
select_round_level = "Technical Round"
search_option_candidate = "Mayara"

round_name = "Technical Round"
round_duration_select = "45 minutes"
round_description = "We will test your technical skills and give an exercise"
round_requirements = "Laptop,Mobile,Headphone"

date_picker = "06/08/2020"
date_check = "13"
free_slot = "11:30 - 12:15"
